config/routes.rb
Greybouquet::Application.routes.draw do

  root :to => 'comics#show'

  namespace :gerbil do
    resources :comics, :casts
    root :to => 'comics#index'
  end
  resources :comics

  resources :casts

end

app/models/cast.rb
class Cast < ActiveRecord::Base
  attr_accessible :description, :name, :likes, :dislikes, :dreams, :headshot
  has_attached_file :headshot, :styles => { :medium => "300x300>", :thumb => "100x100>" },
      :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
      :url => "/system/:attachment/:id/:style/:filename"
end

app/models/comic.rb
class Comic < ActiveRecord::Base
  attr_accessible :series, :strip, :sequence
  has_attached_file :strip, :styles => { :medium => "300x300>", :thumb => "100x100>" },
      :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
      :url => "/system/:attachment/:id/:style/:filename"

  scope :gags, where(:series => 'gag')

  def self.latest
    order(:sequence).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/casts_controller.rb
class CastsController < ApplicationController
  # GET /casts
  # GET /casts.json
  def index
    @casts = Cast.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @casts }
    end
  end

  # GET /casts/1
  # GET /casts/1.json
  def show
    @cast = Cast.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cast }
    end
  end
 end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  # GET /comics
  # GET /comics.json
  def index
    @comics = Comic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comics }
    end
  end

  # GET /comics/1
  # GET /comics/1.json
  def show
    @comic = Comic.find_by_id(params[:id]) || 
      Comic.gags.latest

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comic }
    end
  end
 end

app/controllers/gerbil/casts_controller.rb
class Gerbil::CastsController < ApplicationController
  # GET /casts
  # GET /casts.json
  def index
    @casts = Cast.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @casts }
    end
  end

  # GET /casts/1
  # GET /casts/1.json
  def show
    @cast = Cast.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cast }
    end
  end

  # GET /casts/new
  # GET /casts/new.json
  def new
    @cast = Cast.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cast }
    end
  end

  # GET /casts/1/edit
  def edit
    @cast = Cast.find(params[:id])
  end

  # POST /casts
  # POST /casts.json
  def create
    @cast = Cast.new(params[:cast])

    respond_to do |format|
      if @cast.save
        format.html { redirect_to @cast, notice: 'Cast was successfully created.' }
        format.json { render json: @cast, status: :created, location: @cast }
      else
        format.html { render action: "new", notice: "Could not comply: #{@cast.errors}" }
        format.json { render json: @cast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /casts/1
  # PUT /casts/1.json
  def update
    @cast = Cast.find(params[:id])

    respond_to do |format|
      if @cast.update_attributes(params[:cast])
        format.html { redirect_to @cast, notice: 'Cast was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit", notice: "Could not comply: #{@cast.errors}"  }
        format.json { render json: @cast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /casts/1
  # DELETE /casts/1.json
  def destroy
    @cast = Cast.find(params[:id])
    @cast.destroy

    respond_to do |format|
      format.html { redirect_to gerbil_casts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/gerbil/comics_controller.rb
class Gerbil::ComicsController < ApplicationController
  # GET /comics
  # GET /comics.json
  def index
    @comics = Comic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comics }
    end
  end

  # GET /comics/1
  # GET /comics/1.json
  def show
    @comic = Comic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comic }
    end
  end

  # GET /comics/new
  # GET /comics/new.json
  def new
    @comic = Comic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comic }
    end
  end

  # GET /comics/1/edit
  def edit
    @comic = Comic.find(params[:id])
  end

  # POST /comics
  # POST /comics.json
  def create
    @comic = Comic.new(params[:comic])

    respond_to do |format|
      if @comic.save
        format.html { redirect_to @comic, notice: 'Comic was successfully created.' }
        format.json { render json: @comic, status: :created, location: @comic }
      else
        format.html { render action: "new" }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comics/1
  # PUT /comics/1.json
  def update
    @comic = Comic.find(params[:id])

    respond_to do |format|
      if @comic.update_attributes(params[:comic])
        format.html { redirect_to gerbil_comics_path, notice: 'Comic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comics/1
  # DELETE /comics/1.json
  def destroy
    @comic = Comic.find(params[:id])
    @comic.destroy

    respond_to do |format|
      format.html { redirect_to comics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casts_helper.rb
module CastsHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/views/casts/index.html.erb
<h1>Cast</h1>

<% @casts.each do |cast| %>
  <ul>
    <li><%= image_tag cast.headshot.url(:thumb) %></li>
    <li><%= cast.name %></li>
  </ul>
<% end %>

app/views/casts/index.html.haml
%h1 Cast
%ul.casts
  - @casts.each do |cast|
    %li= image_tag cast.headshot.url(:thumb)
    %li= cast.name

app/views/casts/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @cast.headshot.url %>

<p>
  <b>Name:</b>
  <%= @cast.name %>
</p>

<p>
  <b>Description:</b>
  <%= @cast.description %>
</p>

<p>
  <b>Likes:</b>
  <%= @cast.likes %>
</p>

<p>
  <b>Dislikes:</b>
  <%= @cast.dislikes %>
</p>

<p>
  <b>Dreams and Goals:</b>
  <%= @cast.dreams %>
</p>

<%#<% if current_user = gerbil %>%>
  <%#<%= link_to 'Edit', gerbil_edit_cast_path(@cast) %> |%>
  <%#<%= link_to 'Back', gerbil_casts_path %>%>
<%#<% else %>%>
  <%= link_to 'Back', casts_path %>
<%#<% end %>%>

app/views/comics/index.html.erb
<h1>Comics</h1>

<table>
  <tr>
    <th>Series</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comics.each do |comic| %>
  <tr>
    <td><%= comic.series %></td>
    <td><%= comic.sequence %></td>
    <td><%= image_tag comic.strip.url(:medium) %></td>
    <td><%= link_to 'Show', comic %></td>
  </tr>
<% end %>
</table>

app/views/comics/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @comic.strip.url %>

<p>
  <b>Series:</b>
  <%= @comic.series %>
</p>

<%#<% if current_user == gerbil %>%>
  <%#<%= link_to 'Edit', gerbil_edit_comic_path(@comic) %> |%>
  <%#<%= link_to 'Back', gerbil_comic_path %>%>
<%#<% else %>%>
  <%= link_to 'Back', comics_path %>
<%#<% end %>%>

app/views/gerbil/casts/_form.html.erb
<%= form_for @cast, :url => url, :html => { :multipart => true } do |f| %>
  <% if @cast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cast.errors.count, "error") %> prohibited this cast from being saved:</h2>

      <ul>
      <% @cast.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :likes%><br />
    <%= f.text_area :likes %>
  </div>
  <div class="field">
    <%= f.label :dislikes %><br />
    <%= f.text_area :dislikes %>
  </div>
  <div class="field">
    <%= f.label :dreams %><br />
    <%= f.text_area :dreams %>
  </div>
  <div class="field">
    <% if @cast.headshot? %>
      <%= image_tag @cast.headshot.url(:thumb) %>
    <% end %>
    <%= f.file_field :headshot %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gerbil/casts/edit.html.erb
<h1>Editing cast</h1>

<%= render 'form', :url => gerbil_cast_path(@cast), :method => :post %>

<%= link_to 'Show', @cast %> |
<%= link_to 'Back', gerbil_casts_path %>

app/views/gerbil/casts/index.html.erb
<%= render :partial => "layouts/gerbil_navbar" %>

<h1>Cast</h1>

<table>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Description</th>
    <th>Likes</th>
    <th>Dislikes</th>
    <th>Dreams & Goals</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @casts.each do |cast| %>
  <tr>
    <td><%= image_tag cast.headshot.url(:thumb) %>
    <td><%= cast.name %></td>
    <td><%= cast.description %></td>
    <td><%= cast.likes %>
    <td><%= cast.dislikes %>
    <td><%= cast.dreams %>    
    <td><%= link_to 'Show', cast %></td>
    <td><%= link_to 'Edit', edit_gerbil_cast_path(cast) %></td>
    <td><%= link_to 'Destroy', [:gerbil, cast] , method: :delete, data: { confirm: 'Are you sure?' }%></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cast', new_gerbil_cast_path %>

app/views/gerbil/casts/new.html.erb
<h1>New cast</h1>

<%= render 'form', :url => gerbil_casts_path, :method => :post %>

<%= link_to 'Back', gerbil_casts_path %>

app/views/gerbil/casts/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @cast.headshot.url %>

<p>
  <b>Name:</b>
  <%= @cast.name %>
</p>

<p>
  <b>Description:</b>
  <%= @cast.description %>
</p>

<p>
  <b>Likes:</b>
  <%= @cast.likes %>
</p>

<p>
  <b>Dislikes:</b>
  <%= @cast.dislikes %>
</p>

<p>
  <b>Dreams and Goals:</b>
  <%= @cast.dreams %>
</p>

<%= link_to 'Edit', edit_gerbil_cast_path(@cast) %> |
<%= link_to 'Back', gerbil_casts_path %>

app/views/gerbil/comics/_form.html.erb
<%= form_for @comic, :url => url, :html => { :multipart => true } do |f| %>
  <% if @comic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comic.errors.count, "error") %> prohibited this comic from being saved:</h2>

      <ul>
      <% @comic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :series %><br />
    <%= f.text_field :series %>
  </div>
  <div class="field">
    <%= f.label :sequence %><br />
    <%= f.text_field :sequence %>
  <div class="field">
    <% if @comic.strip? %>
      <%= image_tag @comic.strip.url(:medium) %>
    <% end %>
    <%= f.file_field :strip %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gerbil/comics/edit.html.erb
<h1>Editing comic</h1>

<%= render 'form', :url => gerbil_comic_path(@comic), :method => :put %>

<%= link_to 'Show', @comic %> |
<%= link_to 'Back', gerbil_comics_path %>

app/views/gerbil/comics/index.html.erb
<%= render :partial => "layouts/gerbil_navbar" %>

<h1>Comics</h1>

<table>
  <tr>
    <th>Series</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comics.each do |comic| %>
  <tr>
    <td><%= comic.series %></td>
    <td><%= comic.sequence %></td>
    <td><%= image_tag comic.strip.url(:medium) %></td>
    <td><%= link_to 'Show', comic %></td>
    <td><%= link_to 'Edit', edit_gerbil_comic_path(comic) %></td>
    <td><%= link_to 'Destroy', [:gerbil, comic], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comic', new_gerbil_comic_path %>

app/views/gerbil/comics/new.html.erb
<h1>New comic</h1>

<%= render 'form', :url => gerbil_comics_path, :method => :post %>

<%= link_to 'Back', gerbil_comics_path %>

app/views/gerbil/comics/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @comic.strip.url %>

<p>
  <b>Series:</b>
  <%= @comic.series %>
</p>


<%= link_to 'Edit', edit_comic_path(@comic) %> |
<%= link_to 'Back', comics_path %>

app/views/layouts/_gerbil_navbar.html.haml
#gerbil-nav
  %ul
    %li= link_to 'Comics', gerbil_comics_path
    %li= link_to 'Cast', gerbil_casts_path

app/views/layouts/_navbar.html.haml
%ul#nav
  %li= link_to 'Cast', casts_path
  %li= link_to 'Comics', comics_path
  -#%li= link_to 'Cordyceps Tickles', portal_path, :locals => "CT"
  -#%li= link_to 'Shop', portal_path, :locals => "Shop"
  -#%li= link_to 'Blog',portal_path, :locals => "Blog"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Greybouquet</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render :partial => 'layouts/navbar' %>

<%= yield %>

</body>
</html>